name: Primeiro Workflow

# Executa sempre que houver um push no repositório
on:
  push:
    branches:
      - main
      - master

jobs:
  executar-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Executar comandos de teste
        run: |
          echo "Pipeline executada com sucesso!"
          echo "Versão do Node instalada:"
          node -v
          echo "Listando os arquivos do projeto:"
          ls -la